import type { Metadata } from "next";
import localFont from "next/font/local";
import { NavBar } from "./components/NavBar";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import { Footer2 } from "./components/Footer2";
import "./globals.css";

const enbyGertrude = localFont({
  src: [
    {
      path: "../fonts/typotheque/Enby_Gertrude_roman.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-enby-gertrude",
  display: "swap",
});

const josaFronde = localFont({
  src: [
    {
      path: "../fonts/typotheque/Josafronde-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-josafronde-regular",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Jeremy Bocquet",
  description: "Generated by create next app and writing by bsuareztiret",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${enbyGertrude.variable} ${josaFronde.variable}`}>
        <Header />
        <NavBar />
        <main className="main">
          {children}
          {/*<Footer />*/}
          <Footer2 />
        </main>
      </body>
    </html>
  );
}
