name: Deploy to Levv

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set tag
        id: vars
        run: echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push AMD64 image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t slaar/jijiwebsite:${TAG} .

      - name: Install Levv CLI
        run: |
          curl https://releases.levv.io/install.sh | bash

      - name: Deploy to Levv
        env:
          LEVV_AUTH: ${{ secrets.LEVV_AUTH }}
        run: |
          levv apply -f docker-compose.yaml -p jeremy-website
